//VARIABLES (UNA CAJA DONDE SE GUARDA INFO CON NOMBRE QUE QUEDA GUARDADO Y SE PUEDE ACCEDER CUANDO SEA NECESARIO)
//EXISTEN DOS TIPOS DE VARIABLES LET Y CONST (SOLO EXISTEN Y FUNCIONAN DENTRO DEL BLOQUE OSEA DENTRO DE LLAVES {})

//LET : SE PUEDEN CAMBIAR SU VALOR ES UNA PALABRA RESERVADA (SE DECLARA PONIENDOLE UN NOMBRE ej: let nombresignificativo; QUE SOLO PUEDE ESTAR FORMADO POR LETRAS, NUMEROS Y LOS SIGNOS $ Y _ PERO NO PUEDE EMPEZAR CON UN NUERO NI DEBE CONTENER Ñ Y DIFERENCIA ENTRE MIN Y MAY) 
let ejemplo = "mivariable";
let miApodo = "me";

//CONST: NO PUEDE CAMBIAR SU VALOR 